// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:0ae5faff-b2d5-49be-9309-391a9652162c',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'videoprojectprod-hosting-mobilehub-1975111630',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1r2jfef8v6bk5.cloudfront.net',
    'aws_mobile_analytics_app_id': '20307070ec0d4b19995dc4d7d972258c',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '2b5f1b9d-c73a-435f-a4e8-2c4185192a6a',
    'aws_project_name': 'video-project-prod-2018-11-05-19-27-08',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'videoprojectprod-mobilehub-1975111630',
}

export default awsmobile;
